[package]
name = "python_wrapper"
version = "0.1.0"
edition = "2021"

[lib]
name = "py_viban"
crate-type = ["cdylib"]

[dependencies]
core_iban_valid = {path = "../core_iban_valid" }
maturin = "=1.7.1"
pyo3 = {version = "0.21" ,  features = ["extension-module"] }
ureq = "=2.9.7"
