[workspace]
resolver = "2"


members = [ 
    "iban_validation_rs",
    "iban_validation_py",
    "iban_validation_polars",
    "iban_validation_bench_rs",
    "iban_validation_c"]
default-members = ["iban_validation_rs"]

[workspace.package]
version = "0.1.15"
edition = "2024"
