name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 0.1.0)'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set Up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Remove Existing Wheels
      run: |
        find . -name "*.whl" -type f -delete
        find . -name "*.tar.gz" -type f -delete

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install maturin twine
        pip install -r requirements-python.txt

    - name: Build Python Package
      run: maturin build -m iban_validation_py/Cargo.toml --release

    - name: Build Polars Plugin
      run: maturin build -m iban_validation_polars/Cargo.toml --release

    - name: Publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload target/wheels/*.whl \
          --username __token__ \
          --password ${{ secrets.PYPI_TOKEN }}

    - name: Publish to Crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        cargo publish -p iban_validation_rs

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        files: |
          target/wheels/*.whl
          target/wheels/*.tar.gz
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}